version: "3.8"
services:
  chat:
    container_name: chat
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/usr/src/app/logs
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      .env
    command:
      - ./main

  nginx:
    build: ./deploy/nginx
    container_name: nginx_container
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./deploy/nginx/default:/etc/nginx/sites-available/default
      - ./deploy/nginx/default:/etc/nginx/sites-enabled/default
      - ./deploy/nginx/certs:/etc/nginx/certs
      - ./deploy/nginx/logs:/var/log/nginx
    depends_on:
      - chat
#  postgres:
#    image: postgres:latest
#    container_name: postgres_db
#    env_file:
#      - .env
#    ports:
#      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

#volumes:
#  postgres_data:
