app:
  ver: 1.0

server:
  port: 8080
  address: 127.0.0.1
  type: tcp
  mode: 1 # 1 = release, 2 = debug

logger:
  path: logs/prod.log
  level: 1 # 1 = release, 2 = debug

postgres:
  host: localhost
  port: 5432
  user: amir
  database: chat
  sslmode: disable
  max_conn_attempts: 5
  maxconn: 100
  max_conn_delay: 5 # seconds